### ISSUE TITLE
设置tooltip后显示异常

### ISSUE THREAD

**Issue by zhuhaoxlj** [mcxinyu/echarts-android#2]
![image](https://user-images.githubusercontent.com/56185765/223598758-9916d035-32ff-4d27-9c41-078137f59af0.png)
![image](https://user-images.githubusercontent.com/56185765/223598765-b952dbaa-5de2-412f-9d21-0a24917f70ee.png)

**Comment by mcxinyu** [comment]
是啊，我也发现了，但是这应该是 echarts 在 Android WebView 上渲染的问题。请关注 [echarts issues](https://github.com/apache/echarts/issues?q=+tooltip) ，或提交一个 [new issues](https://github.com/apache/echarts/issues/new?assignees=&labels=bug&template=bug_report.yml&title=%5BBug%5D+)。

**Comment by zhuhaoxlj** [comment]
> 
这个是我用 Android 浏览器直接渲染的 html，然后数据通过 url 传进来的，暂时只能用这种办法啦🥹
![image](https://user-images.githubusercontent.com/56185765/224196494-94475990-a380-4859-bc6e-3dcca00a1e31.png)

**Comment by mcxinyu** [comment]
我想可能跟 webview 或者 html 设置视口大小有关，可以跟前端同学讨论一下，如果有解决办法请及时通知我跟进。

**Comment by mcxinyu** [comment]
因为 echarts 是开源的，深入源码应该能看到确定 tooltip 大小的策略。

**Comment by zhuhaoxlj** [comment]
> 因为 echarts 是开源的，深入源码应该能看到确定 tooltip 大小的策略。

好的，感谢，如果有进展会及时反馈🌷

**Comment by XDao7** [comment]
问题出在这一句上面：
```
<style type="text/css">body, html, div {height: 100%;width: 100%;margin: 0;}div {-webkit-tap-highlight-color: rgba(255, 255, 255, 0);}</style>
```
tooltip本身是个div，这里面直接设置成最大了，把height: 100%;width: 100%;margin: 0;放到用来放echarts的那个div上面，tooltip就正常了。
